package com.JobController.worker;

/**
 * Represents one live session of a worker process.
 *
 * <p>Each time a worker process (re)starts it receives a new {@code incarnationId}.
 * This allows the controller to distinguish heartbeats from the old process from those
 * of the restarted process, even when both use the same {@code workerUUID}.
 *
 * <p>The triple {@code (workerUUID, incarnationId, heartbeatSequence)} is the globally
 * unique identity of every heartbeat message.
 */
public final class WorkerSession {

    /** Logical identity that survives restarts. */
    private final String workerUUID;

    /**
     * Opaque token that changes on every worker-process start.
     * Persistently generated by the worker; monotonically increasing across restarts.
     */
    private final String incarnationId;

    /** Wall-clock time (ms) at which this session was accepted by the controller. */
    private final long registeredAtMillis;

    /** Highest heartbeat sequence number seen for this incarnation. -1 = none yet. */
    private long latestSequence = -1L;

    /** Controller wall-clock time of the most recently accepted heartbeat. */
    private volatile long lastHeartbeatMillis;

    public WorkerSession(String workerUUID, String incarnationId, long registeredAtMillis) {
        this.workerUUID         = workerUUID;
        this.incarnationId      = incarnationId;
        this.registeredAtMillis = registeredAtMillis;
        this.lastHeartbeatMillis = registeredAtMillis;
    }

    // -------------------------------------------------------------------------
    // Heartbeat processing
    // -------------------------------------------------------------------------

    /**
     * Tries to update the session with a new heartbeat.
     *
     * @param sequence the heartbeat sequence sent by the worker
     * @param nowMillis controller-observed receive time
     * @return {@code true} if the heartbeat was accepted (newer or equal sequence),
     *         {@code false} if it was stale (older sequence, i.e. out-of-order / duplicate)
     */
    public synchronized boolean acceptHeartbeat(long sequence, long nowMillis) {
        if (sequence < 0 || sequence <= latestSequence) {
            return false;
        }
        latestSequence = sequence;
        lastHeartbeatMillis = nowMillis;
        return true;
    }

    synchronized void refreshRegistration(long nowMillis) {
        lastHeartbeatMillis = nowMillis;
    }

    // -------------------------------------------------------------------------
    // Accessors
    // -------------------------------------------------------------------------

    public String workerUUID()          { return workerUUID; }
    public String incarnationId()       { return incarnationId; }
    public long registeredAtMillis()    { return registeredAtMillis; }
    public synchronized long latestSequence() { return latestSequence; }
    public synchronized long lastHeartbeatMillis() { return lastHeartbeatMillis; }

    @Override
    public String toString() {
        return "WorkerSession{uuid=" + workerUUID
                + ", incarnation=" + incarnationId
                + ", latestSeq=" + latestSequence()
                + ", lastHB=" + lastHeartbeatMillis() + '}';
    }
}
